name: state_restoration_presentation
description: "a presentation about state restoration for fluttercon berlin 2024"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  dart_style: ^2.3.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_deck: ^0.14.0
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_shader_snap: ^0.0.3
  flutter_svg: ^1.1.6
  graphite: ^1.1.2
  intl: any
  rive: ^0.13.5
  video_player: ^2.9.1

dev_dependencies:
  dart_code_metrics: ^5.7.3
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/what_happened_images/
    - assets/images/why_it_bothered/
    - assets/images/bucket/
    - assets/rive/
    - assets/videos/

  shaders:
    - packages/flutter_shader_snap/shaders/split_snap_effect_shader.glsl

  fonts:
    - family: Graphik
      fonts:
        - asset: assets/fonts/GraphikSemibold.otf
          weight: 600
        - asset: assets/fonts/GraphikMedium.otf
          weight: 500
        - asset: assets/fonts/GraphikRegular.otf
          weight: 400

flutter_gen:
  output: lib/generated
  line_length: 80
  integrations:
    flutter_svg: true
