import 'package:flutter/cupertino.dart';

const emptyPadding = EdgeInsets.zero;
const horizontalPadding2 = EdgeInsets.symmetric(horizontal: 2);
const horizontalPadding4 = EdgeInsets.symmetric(horizontal: 4);
const horizontalPadding8 = EdgeInsets.symmetric(horizontal: 8);
const horizontalPadding12 = EdgeInsets.symmetric(horizontal: 12);
const horizontalPadding16 = EdgeInsets.symmetric(horizontal: 16);
const horizontalPadding24 = EdgeInsets.symmetric(horizontal: 24);
const horizontalPadding32 = EdgeInsets.symmetric(horizontal: 32);
const horizontalPadding48 = EdgeInsets.symmetric(horizontal: 48);
const verticalPadding2 = EdgeInsets.symmetric(vertical: 2);
const verticalPadding4 = EdgeInsets.symmetric(vertical: 4);
const verticalPadding8 = EdgeInsets.symmetric(vertical: 8);
const verticalPadding12 = EdgeInsets.symmetric(vertical: 12);
const verticalPadding16 = EdgeInsets.symmetric(vertical: 16);
const verticalPadding24 = EdgeInsets.symmetric(vertical: 24);
const verticalPadding32 = EdgeInsets.symmetric(vertical: 32);
const verticalPadding48 = EdgeInsets.symmetric(vertical: 48);
const allPadding2 = EdgeInsets.all(2);
const allPadding4 = EdgeInsets.all(4);
const allPadding8 = EdgeInsets.all(8);
const allPadding12 = EdgeInsets.all(12);
const allPadding16 = EdgeInsets.all(16);
const allPadding24 = EdgeInsets.all(24);
const allPadding32 = EdgeInsets.all(32);
const allPadding48 = EdgeInsets.all(48);
